<?php
/**
 * Magento Module developed by NoStress Commerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to info@nostresscommerce.cz so we can send you a copy immediately.
 *
 * @copyright Copyright (c) 2015 NoStress Commerce (http://www.nostresscommerce.cz)
 *
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\AdminNotification\Block\System\Messages\UnreadMessagePopup */ ?>

<div style="display:none" id="help_request" data-role="help_request" title="Help<?php //echo $block->escapeHtml($block->getPopupTitle()); ?>">
    
<div class="entry-edit form-inline">
    <?php echo $block->getFormHtml();?>
</div>
<?php echo $block->getChildHtml('form_after');?>
    
</div>

<script>
require([
    "jquery",
    "Magento_Ui/js/modal/modal",
    'mage/backend/form',
    'mage/backend/validation'
], function($){

	var help_form = $('#help_form').form();
	help_form.validation({
        validationUrl: '<?php /* @escapeNotVerified */ echo $block->getValidationUrl() ?>',
        highlight: function(element) {
            var detailsElement = $(element).closest('details');
            if (detailsElement.length && detailsElement.is('.details')) {
                var summaryElement = detailsElement.find('summary');
                if (summaryElement.length && summaryElement.attr('aria-expanded') === "false") {
                    summaryElement.trigger('click');
                }
            }
            $(element).trigger('highlight.validate');
        }
    });
	
	var modal = null;
    if (modal) {
        modal.html($('[data-role="help_request"]').html());
    } else {
        modal = $('[data-role="help_request"]').modal({
            title: $.mage.__('Get Support'),
            type: 'slide',
            buttons: [
                {
                    text: $.mage.__('Back'),
                    class: 'back',
                    click: function () {
                    	this.closeModal();
                    }
                },
                {
                    text: $.mage.__('Send Request'),
                    class: 'primary',
                    click: function () {
                    	help_form.submit();
                    }
                },
            ]
        });
    }

    $(document).ready(function () {
        $('#help_dialog').on('click', function () {
            modal.modal('openModal');
        });
    });
});
</script>
