<?php
/**
 * Magento Module developed by NoStress Commerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to info@nostresscommerce.cz so we can send you a copy immediately.
 *
 * @copyright Copyright (c) 2015 NoStress Commerce (http://www.nostresscommerce.cz)
 *
 */

// @codingStandardsIgnoreFile

/** @var $block Nostress\Koongo\Block\Adminhtml\Channel\Profile\General\Edit\Tab\Main\Attributes\Info */
?>
    <?php $title = $block->getTitle();?>
    <div class='side-col-block'>
    <?php if(empty($title)): ?>
		<h1><?= /* @escapeNotVerified */  $block->getChannelLabel()." ".__('Attribute')." ";?><strong data-bind="text: attributes()[currentAttributeIndex()].label">Attribute Label</strong></h1>
	<?php else: ?>
		<h3><?php echo $title;?></h3>
	<?php endif;?>
   	    <p data-bind="text: attributes()[currentAttributeIndex()].description.text">Attribute Description</p>
   	    <p data-bind="visible: attributes()[currentAttributeIndex()].description.text == ''"><?= /* @escapeNotVerified */  __('Attribute description not available.');?></p>
   	</div>
         	
   	<div class='side-col-block' data-bind="visible: attributes()[currentAttributeIndex()].description.example">
		<h3><?= /* @escapeNotVerified */  __('Example') ?></h3>
        <p data-bind="text: attributes()[currentAttributeIndex()].description.example">Attribute Example</p>
    </div>
    
    <div class='side-col-block' data-bind="visible: attributes()[currentAttributeIndex()].description.options">
    	<h3><?= /* @escapeNotVerified */  __('Options') ?></h3>
    	
    	<ul data-bind="foreach: attributes()[currentAttributeIndex()].description.option_array">
	   		<li>
	           	<div class="admin__field admin__field-option">
		            <label class="admin__field-label">
		            	<span data-bind="text: value_label"/>
				    </label>
			   	</div>
			</li>
     	</ul>
    </div>




