<?php
/**
 * Magento Module developed by NoStress Commerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to info@nostresscommerce.cz so we can send you a copy immediately.
 *
 * @copyright Copyright (c) 2015 NoStress Commerce (http://www.nostresscommerce.cz)
 *
 */

// @codingStandardsIgnoreFile

?>
<script>
require([
    "jquery",
    "uiRegistry",
    "Magento_Ui/js/modal/alert",
    'Magento_Ui/js/modal/prompt',
    "collapsable",
    "prototype"
], function (jQuery, rg, alert, prompt) 
{
	jQuery( document ).ready(function() 
	{
		//render shipping intervals 0.5s after page load
		setTimeout( function(){ 
			jQuery('#manage-options-panel').trigger('render');
			updateShippingTable($('channel_profile_dependent_attribute'));			
		  }  , 500 );

		//render shipping intervals 3s after page load(to ensure that table is rendered)
		setTimeout( function(){ 
			jQuery('#manage-options-panel').trigger('render');
			updateShippingTable($('channel_profile_dependent_attribute'));			
		  }  , 3000 );	
		  
		//render shipping intervals 10s after page load(to ensure that table is rendered)  
		setTimeout( function(){ 
			jQuery('#manage-options-panel').trigger('render');
			updateShippingTable($('channel_profile_dependent_attribute'));			
		  }  , 10000 );		 					
	});  	  
});

</script>
