<?php
/**
 * Magento Module developed by NoStress Commerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to info@nostresscommerce.cz so we can send you a copy immediately.
 *
 * @copyright Copyright (c) 2015 NoStress Commerce (http://www.nostresscommerce.cz)
 *
 */

// @codingStandardsIgnoreFile

/** @var $block Nostress\Koongo\Block\Adminhtml\Channel\Profile\Filter\Edit\Tab\Main\Categories */
?>

<fieldset class="fieldset" id="<?php echo $block->getFieldsetName();?>">
    <legend class="legend">
        <span>
            <?php /* @escapeNotVerified */ echo __('Categories') ?>
            <?php echo $this->getTooltip(); ?>
        </span>
    </legend>
     <?php echo __("Category filter is active only if at least one category is selected.")?>
     <br/>
     <br/>
     <input id="<?php echo $block->getCategoriesFilterInputId(); ?>" type="hidden" value="<?php echo $block->getCategoryIdsString(); ?>" name=<?php echo $block->getCategoriesFilterInputName();?>/>
     <?php echo $block->getCategoryTreeHtml();?>
</fieldset>

