<?php
/**
 * Magento Module developed by NoStress Commerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to info@nostresscommerce.cz so we can send you a copy immediately.
 *
 * @copyright Copyright (c) 2015 NoStress Commerce (http://www.nostresscommerce.cz)
 *
 */

// @codingStandardsIgnoreFile

/* @var $block \Nostress\Koongo\Block\Adminhtml\Channel\Profile\Create\Steps\Feed */
?>
<div data-bind="scope: '<?= /* @escapeNotVerified */  $block->getComponentName()?>'">
    <h2 class="steps-wizard-title"><?= /* @escapeNotVerified */  __('Step 2: Feed Type') ?></h2>
    <div class="steps-wizard-info">
    	<span><?= /* @escapeNotVerified */  __('Select Feed Type for new export profile.') ?></span>
    </div>
   <div class="steps-wizard-section">
        <div data-role="section">
        	<div class="steps-wizard-section-title">
        		<span data-bind="text: feedTypeSectionName"></span>
        	</div>
       	    <div class="channel_list_container">
            	<ul class="steps-wizard-section-list" data-bind="foreach: feedList">
    	        	<li>
    	                <div class="admin__field admin__field-option">
    			           	<input type="radio" name="feed_code" class="admin__control-radio"
    			           	     data-bind="checked: $parent.isFeedChecked, value: code, attr: { id: id}" />
    	                    <label class="admin__field-label" data-bind="attr: { for: id}">
    	                    	<span data-bind="text: label"></span>
    			        	</label>
    			     	</div>
    			     </li>
                </ul>
            </div>
            <div class="channel_info_container" data-bind="html: channelManual()">
            </div>
		</div>
	</div>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "<?= /* @escapeNotVerified */  $block->getComponentName()?>": {
                        "component": "Nostress_Koongo/js/createprofile/steps/feed",
                        "appendTo": "<?= /* @escapeNotVerified */  $block->getParentComponentName()?>",
						"feedsByLink": <?php echo $block->getFeedsByLink()?>,
						"createProfileUrl": "<?= /* @escapeNotVerified */  $block->getUrl('*/*/create')?>",
                        "manualsByCode": <?php echo json_encode( $block->getChannelManualList()); ?>
                    }
                }
            }
        }
    }
</script>
